#!/bin/bash

set -e  # Exit on error

# Variables
export MENU_VERSION="-Jollyk OneUI 7.0"
export DIR="$(readlink -f .)"
export OUT_DIR="$DIR/out"
export PARENT_DIR="$(readlink -f "$DIR/..")"
export RDIR="$(pwd)"
export MGB="$RDIR"/magiskboot
export RAMDISK_DIR=/home/chanz22/Documentos/GitHub/android_kernel_samsung_r11s/magiskboot/ramdisk_extracted/out_dlkm/lib/modules

export CROSS_COMPILE="$PARENT_DIR/clang-r416183b/bin/aarch64-linux-gnu-"
export CC="$PARENT_DIR/clang-r416183b/bin/clang"

export PLATFORM_VERSION=15
export ANDROID_MAJOR_VERSION=v
export TARGET_SOC=s5e9925
export LLVM=1 LLVM_IAS=1
export ARCH=arm64
export KERNEL_MAKE_ENV="LOCALVERSION=-v1.0"
export KBUILD_BUILD_USER="Chanz22"

export BOARD=SRPWC28A007

# update git submodules
git submodule init && git submodule update

export PATH="$PARENT_DIR/clang-r416183b/bin:$PARENT_DIR/build-tools/path/linux-x86:$PARENT_DIR/gas/linux-x86:$PATH"

# Colors
BOLD_RED=$(tput bold; tput setaf 1)
BOLD_BLUE=$(tput bold; tput setaf 4)
BOLD_GREEN=$(tput bold; tput setaf 2)
UNDERLINE=$(tput smul)
RESET=$(tput sgr0)

# Functions
pause() {
  read -rp "${BOLD_RED}$2${RESET}Press ${BOLD_BLUE}[Enter]${RESET} to $1..."
}

check_and_clone() {
  local repo_url="$1"
  local dest_dir="$2"
  local description="$3"

  if [ ! -d "$dest_dir" ]; then
    pause "clone $description"
    git clone "$repo_url" "$dest_dir"
  fi
}

variant() {
  local configs
  configs=($(ls arch/arm64/configs/exynos2200_r11s_defconfig* 2>/dev/null))

  if [ ${#configs[@]} -eq 0 ]; then
    pause "return to main menu" "No variants found! "
    return
  fi

  echo ""
  echo "${BOLD_BLUE}Variant Selection:${RESET}"
  for i in "${!configs[@]}"; do
    echo " $((i + 1)). $(basename "${configs[i]}" | cut -d'_' -f2)"
  done

  local choice
  read -rp "Enter choice [1 - ${#configs[@]}]: " choice
  if [[ "$choice" =~ ^[0-9]+$ ]] && (( choice > 0 && choice <= ${#configs[@]} )); then
    VARIANT="$(basename "${configs[choice - 1]}" | cut -d'_' -f2)"
    echo "Variant ${VARIANT} selected"
    pause "continue"
  else
    pause "return to main menu" "Invalid option, "
  fi
}

clean() {
  echo "${BOLD_GREEN}***** Cleaning directories *****${RESET}"
  make clean && make mrproper
  rm -rf "$OUT_DIR"
  echo "${BOLD_GREEN}***** Cleaning complete *****${RESET}"
  pause "continue"
}

build_kernel() {
  variant
  echo "${BOLD_GREEN}***** Compiling kernel *****${RESET}"
  mkdir -p "$OUT_DIR"

  make -j8 -C "$(pwd)" $KERNEL_MAKE_ENV "exynos2200_${VARIANT}_defconfig" dtbs
  make -j8 -C "$(pwd)" $KERNEL_MAKE_ENV

  # Generate dtbo and dtb
  ./toolchain/mkdtimg cfg_create out/dtbo.img dtconfigs/r11s.cfg -d arch/arm64/boot/dts/samsung/r11s
  ./toolchain/mkdtimg cfg_create out/dtb.img dtconfigs/exynos2200.cfg -d arch/arm64/boot/dts/exynos

  if [ -e "$DIR/arch/arm64/boot/Image.gz" ]; then
    cp "$DIR/arch/arm64/boot/Image.gz" "$OUT_DIR/Image.gz"
  fi

  if [ -e "$DIR/arch/arm64/boot/Image" ]; then
    cp "$DIR/arch/arm64/boot/Image" "$OUT_DIR/Image"
    echo "${BOLD_GREEN}***** Ready to flash! *****${RESET}"
    pause "continue"
  else
    pause "return to main menu" "Kernel build failed!"
  fi
}

anykernel3() {
  variant
  if [ -e "$DIR/arch/arm64/boot/Image" ]; then
    cd AnyKernel3 || exit
	rm -rf *.zip
    cp "$DIR/arch/arm64/boot/Image" Image
    cp "$DIR/out/dtbo.img" dtbo
    cp "$DIR/out/dtb.img" dtb
    zip -r9 "${VARIANT}_kernel_$(cat "$DIR/include/config/kernel.release")_$(date '+%Y_%m_%d').zip" * -x .git README.md *placeholder
    cd "$DIR" || exit
    pause "continue"
  else
    pause "return to main menu" "Build the kernel first! "
  fi
}

build_vendor_boot() {
  echo "${BOLD_GREEN}***** Building vendor_boot image *****${RESET}"
  
  # Verificar se o vendor_boot.img original existe
  if [ ! -e "$MGB/images/vendor_boot/vendor_boot.img" ]; then
    echo "${BOLD_RED}[!] Error: vendor_boot.img not found at $MGB/images/vendor_boot/vendor_boot.img${RESET}"
    pause "return to main menu"
    return
  fi

  cd "$MGB" || exit
  
  # Clean up previous work
  ./magiskboot cleanup 2>/dev/null || true
  
  # Copy and unpack vendor_boot
  cp "$MGB/images/vendor_boot/vendor_boot.img" vendor_boot.img
  if ! ./magiskboot unpack vendor_boot.img; then
    echo "${BOLD_RED}[!] Error: Failed to unpack vendor_boot.img${RESET}"
    cd "$DIR" || exit
    pause "return to main menu"
    return
  fi

  # Replace dtb
  rm -f dtb
  if [ -e "$DIR/out/dtb.img" ]; then
    cp "$DIR/out/dtb.img" dtb
    echo "[*] DTB replaced successfully"
  else
    echo "${BOLD_RED}[!] Warning: dtb.img not found at $DIR/out/dtb.img${RESET}"
  fi

  # Repack vendor_boot
  if ./magiskboot repack vendor_boot.img; then
    # Move the new image to output directory
    mkdir -p "$OUT_DIR"
    mv "$MGB/new-boot.img" "$OUT_DIR/vendor_boot-$(date '+%Y%m%d').img"
    echo "${BOLD_GREEN}[+] vendor_boot image created successfully!${RESET}"
    echo "[*] Output: $OUT_DIR/vendor_boot-$(date '+%Y%m%d').img"
  else
    echo "${BOLD_RED}[!] Error: Failed to repack vendor_boot.img${RESET}"
  fi

  ./magiskboot cleanup
  cd "$DIR" || exit
  pause "continue"
}

build_modules() {
    MODULES_FOLDER=modules
    rm -rf out/$MODULES_FOLDER
    mkdir build/out/$MODEL/modules_dlkm

    echo "-----------------------------------------------"
    echo "Building modules..."
    # Strip modules and place them in modules folder
    make ${MAKE_ARGS} INSTALL_MOD_PATH=$MODULES_FOLDER INSTALL_MOD_STRIP=1 modules_install || abort

    # List of kernel modules to remove
    # Some of the kernel modules are in /vendor_dlkm or /vendor/lib/modules and not in vendor_boot
    # So we will remove them from the folder and run depmod again to update the files
    # TODO: Generate a /vendor_dlkm partition as well
    # The filenames were fetched from vendor_module_list_s5e9925.cfg and vendor_module_list_s5e9925_b0s.cfg.
    FILENAMES="
    sec_debug_coredump.ko
    fingerprint.ko
    fingerprint_sysfs.ko
    input_booster_lkm.ko
    dhd.ko
    wlan.ko
    "
    for FILENAME in $FILENAMES; do
        FILE=$(find out/$MODULES_FOLDER -type f -name "$FILENAME")
        cp "$FILE" "build/out/r11s/modules_dlkm" 2>/dev/null
        rm -f "$FILE"
    done

    # Now we run depmod to update the dep/softdep files
    # For this we need the kernel version
    KERNEL_DIR_PATH=$(find "out/$MODULES_FOLDER/lib/modules" -maxdepth 1 -type d -name "5.10*") || abort
    KERNEL_VERSION=$(basename $KERNEL_DIR_PATH) || abort

    # And finally depmod itself
    depmod -a -b out/$MODULES_FOLDER $KERNEL_VERSION || abort

    # depmod updates modules.alias, modules.dep and modules.softdep
    # But the module order is not updated by depmod
    # We have to remove the filenames ourselves
    # But first, our vendor_boot needs modules.order definitions that go like:
    # fingerprint.ko
    # Clang generates modules.order definitions like this
    # kernel/drivers/fingerprint/fingerprint.ko
    # So we sed the file to adapt
    sed -i 's/.*\///g' $KERNEL_DIR_PATH/modules.order 

    # Now we sed the bad filenames out of the file with a loop
    for FILENAME in $FILENAMES; do
        sed -i "/$FILENAME/d" "$KERNEL_DIR_PATH/modules.order"
    done

    # Now we have to order the modules
    # Samsung was nice enough to give us the order in vendor_boot_module_order_s5e9925.cfg
    # exynos-chipid_v2.ko exynos-reboot.ko sec_debug_base_early.ko clk_exynos.ko exynos_mct_v2.ko s3c2410_wdt.ko sec_debug_mode.ko
    # These files have to be at the top of modules.order in this order, and then we can keep the default order.
    # Samsung wants the file to be renamed to modules.load anyways, so we will craft our own modules.load file based on modules.order
    touch $KERNEL_DIR_PATH/modules.load

    INITIAL_ORDER="
    exynos-chipid_v2.ko
    exynos-reboot.ko
    sec_debug_base_early.ko
    clk_exynos.ko
    exynos_mct_v2.ko
    s3c2410_wdt.ko
    sec_debug_mode.ko
    "

    # First we add the order from Samsung into our new modules.load
    # And we sed it out of modules.order
    for LINE in $INITIAL_ORDER; do
        echo $LINE >> $KERNEL_DIR_PATH/modules.load
        sed -i "/$LINE/d" "$KERNEL_DIR_PATH/modules.order"
    done

    # Now we add the remaining lines from modules.order into modules.load
    while IFS= read -r line; do
        echo "$line" >> "$KERNEL_DIR_PATH/modules.load"
    done < "$KERNEL_DIR_PATH/modules.order"

    # Now we have to also modify modules.dep
    # Android generates them like this
    # kernel/drivers/dma/samsung-dma.ko: kernel/drivers/dma/pl330.ko
    # But Samsung wants them like this
    # /lib/modules/samsung-dma.ko: /lib/modules/pl330.ko
    # So we will format it with sed
    sed -i 's/\(kernel\/[^: ]*\/\)\([^: ]*\.ko\)/\/lib\/modules\/\2/g' "$KERNEL_DIR_PATH/modules.dep"

    # Now the modules and their configuration descriptor files are ready, we move them to a folder and create the new second ramdisk
    # The second ramdisk should contain a /lib/modules where the modules are located
    mkdir -p build/out/r11s/modules/lib/modules

    find $KERNEL_DIR_PATH -name '*.ko' -exec cp '{}' build/out/r11s/modules/lib/modules ';'

    # We also copy the module configuration descriptors
    cp $KERNEL_DIR_PATH/modules.{alias,dep,softdep,load} build/out/r11s/modules/lib/modules
}

build_vendor_boot() {
    echo "-----------------------------------------------"
    echo "Building vendor_boot RAMDisks..."
    # Copy common vendor_ramdisk00 files to build/out
    cp -a build/ramdisk/vendor_boot/ramdisk00 build/out/r11s/vendor_ramdisk00
    
    # Copy device firmware files for vendor_ramdisk00
    cp -a build/ramdisk/vendor_boot/vendor_firmware/r11s/* build/out/r11s/vendor_ramdisk00

    # Pack RAMDisks
    # vendor_ramdisk == ramdisk00
    # modules_ramdisk == ramdisk01
    pushd build/out/$MODEL/vendor_ramdisk00 > /dev/null
    find . ! -name . | LC_ALL=C sort | cpio -o -H newc -R root:root | lz4 -l > ../$MODEl/vendor_ramdisk || abort
    popd > /dev/null

    pushd build/out/$MODEL/modules > /dev/null
    find . ! -name . | LC_ALL=C sort | cpio -o -H newc -R root:root | lz4 -l > ../modules_ramdisk || abort
    popd > /dev/null

    echo "-----------------------------------------------"
    echo "Building vendor_boot image..."

    OUTPUT_FILE=build/out/r11s/vendor_boot.img
    DTB_PATH=build/out/r11s/dtb.img
    BOOTCONFIG_PATH=build/ramdisk/bootconfig
    RAMDISK_00=build/out/r11s/vendor_ramdisk
    RAMDISK_01=build/out/r11s/modules_ramdisk
    HEADER_VERSION=4
    BASE=0x00000000
    PAGESIZE=0x00001000
    KERNEL_OFFSET=0x10008000
    RAMDISK_OFFSET=0x14000000
    TAGS_OFFSET=0x10000000
    DTB_OFFSET=0x0000000011F00000
    CMDLINE="bootconfig loop.max_part=7"

    python3 toolchain/mkbootimg/mkbootimg.py --header_version $HEADER_VERSION --pagesize $PAGESIZE --base $BASE --kernel_offset $KERNEL_OFFSET \
	--ramdisk_offset $RAMDISK_OFFSET --tags_offset $TAGS_OFFSET --dtb_offset $DTB_OFFSET --vendor_cmdline "$CMDLINE" --board $BOARD --dtb $DTB_PATH  \
	--ramdisk_type 1 --ramdisk_name "" --vendor_ramdisk_fragment $RAMDISK_00 --vendor_bootconfig $BOOTCONFIG_PATH --ramdisk_type 3 \
	--ramdisk_name dlkm --vendor_ramdisk_fragment $RAMDISK_01 --vendor_boot $OUTPUT_FILE || abort
}

build_boot_image() {
  if [ -e "$MGB/images/boot/boot.img" ]; then
    cd "$MGB" || exit
    cp "$MGB/images/boot/boot.img" boot.img
    ./magiskboot unpack boot.img
    rm -rf kernel
    cp "$DIR/arch/arm64/boot/Image" kernel
    ./magiskboot repack boot.img
    mv "$MGB/new-boot.img" "$OUT_DIR/Jelly_boot-$(date '+%Y_%m_%d').img"
    echo "boot image done!"
    ./magiskboot cleanup
    cd "$DIR" || exit
    read -p "Press enter to continue..."
  else
    read -p "Error!" "the boot image was not found in the specified path! Press enter to continue..."
  fi
}

install_dependencies() {
  echo "${BOLD_GREEN}***** Installing build dependencies *****${RESET}"
  sudo apt-get install git ccache automake lzop gperf build-essential zip curl zlib1g-dev g++-multilib libxml2-utils bzip2 libbz2-dev libbz2-1.0 libghc-bzlib-dev squashfs-tools pngcrush schedtool dpkg-dev make optipng flex bison gcc clang lld libncurses-dev libssl-dev libelf-dev -y
  echo "${BOLD_GREEN}***** Dependencies installation complete *****${RESET}"
  pause "continue"
}

# Run dependency checks
check_and_clone "https://github.com/crdroidandroid/android_prebuilts_clang_host_linux-x86_clang-r416183b" "$PARENT_DIR/clang-r416183b" "Android Clang/LLVM"
check_and_clone "https://android.googlesource.com/platform/prebuilts/gas/linux-x86" "$PARENT_DIR/gas/linux-x86" "GNU assembler"
check_and_clone "https://android.googlesource.com/platform/prebuilts/build-tools" "$PARENT_DIR/build-tools" "Build tools"

# Menu
show_menus() {
  clear
  echo "${BOLD_BLUE} S23FE Kernel builder V2.0 $MENU_VERSION${RESET}"
  echo " 1. ${UNDERLINE}Build${RESET} Kernel"
  echo " 2. ${UNDERLINE}Clean${RESET} directories"
  echo " 3. Create ${UNDERLINE}Flashable ZIP${RESET}"
  echo " 4. Generate ${UNDERLINE}vendor_boot image${RESET}"
  echo " 5. update ${UNDERLINE}vendor_dlmk.cpio${RESET}"
  echo " 6. Generate ${UNDERLINE}boot image${RESET}"
  echo " 7. ${UNDERLINE}Install Build Dependencies${RESET}"
  echo " 8. ${UNDERLINE}Exit${RESET}"
}

read_options() {
  local choice
  read -rp "Enter choice [1-7]: " choice
  case $choice in
    1) build_kernel ;;
    2) clean ;;
    3) anykernel3 ;;
    4) build_vendor_boot ;;
    5) update_vendor_dlkm ;;
    6) build_boot_image ;;
    7) install_dependencies ;;
    8) exit 0 ;;
    *) pause "return to menu" "Invalid option! " ;;
  esac
}

while true; do
  show_menus
  read_options
done
